/*
 * Test data strategy for MyPerson.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2020-05-23 16:24 +0800.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for MyPerson. Provides
 * instances of MyPerson for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2020-05-23 16:24 +0800
 */
public /*@ nullable_by_default */ class MyPerson_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of MyPerson.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add MyPerson values or generators here */ });
  }

  /**
   * @return default instances of MyPerson, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<MyPerson> defaultValues() {
    final List<RepeatedAccessIterator<MyPerson>> iters = 
      new LinkedList<RepeatedAccessIterator<MyPerson>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<MyPerson>
      (MyPerson.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method MyPerson(int, String, BigInteger, int)
    iters.add(new InstantiationIterator<MyPerson>
      (MyPerson.class, 
       new Class<?>[]
       {int.class, 
        java.lang.String.class, 
        java.math.BigInteger.class, 
        int.class},
       MyPerson_JML_Test.p_MyPerson__int_id__String_name__BigInteger_character__int_age__20().wrapped()));

    return new NonNullMultiIterator<MyPerson>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public MyPerson_InstanceStrategy() {
    super(MyPerson.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
