/*
 * Test data strategy for MyPerson.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2020-05-23 16:24 +0800.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for MyPerson. Provides
 * test values for parameter "String name" 
 * of method "MyPerson(int, String, BigInteger, int)". 
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2020-05-23 16:24 +0800
 */
public /*@ nullable_by_default */ class MyPerson_MyPerson__int_id__String_name__BigInteger_character__int_age__20__name
  extends MyPerson_ClassStrategy_java_lang_String {
  /**
   * @return local-scope values for parameter 
   *  "String name".
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add local-scope java.lang.String values or generators here */ });
  }
}
