/*
 * Test data strategy for Runner.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2020-05-23 16:24 +0800.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for Runner. Provides
 * instances of Runner for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2020-05-23 16:24 +0800
 */
public /*@ nullable_by_default */ class Runner_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of Runner.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add Runner values or generators here */ });
  }

  /**
   * @return default instances of Runner, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<Runner> defaultValues() {
    final List<RepeatedAccessIterator<Runner>> iters = 
      new LinkedList<RepeatedAccessIterator<Runner>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<Runner>
      (Runner.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method Runner(Class, Class, Class)
    iters.add(new InstantiationIterator<Runner>
      (Runner.class, 
       new Class<?>[]
       {java.lang.Class.class, 
        java.lang.Class.class, 
        java.lang.Class.class},
       Runner_JML_Test.p_Runner__Class_personClass__Class_networkClass__Class_groupClass__30().wrapped()));

    return new NonNullMultiIterator<Runner>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public Runner_InstanceStrategy() {
    super(Runner.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
